name: Deploy to EC2

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build application
      run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/app
          git pull origin main
          
          # Clean install to avoid peer dependency issues
          rm -rf node_modules package-lock.json
          npm install --production
          
          npm run db:generate
          npm run db:push
          pm2 reload ems-backend || pm2 start server/index.js --name ems-backend
          pm2 save
          
          # Simple health check
          sleep 5
          if curl -f http://localhost:3001/api/health; then
            echo "✅ Deployment successful"
          else
            echo "❌ Health check failed"
            pm2 logs ems-backend --lines 10
            exit 1
          fi